osx_image: xcode9.2
language: objective-c
xcode_workspace: HMRequestFramework.xcworkspace
xcode_scheme: HMRequestFramework
xcode_sdk: iphonesimulator11.2
before_install:
- gem install cocoapods slather xcpretty
- pod repo update

script:
- set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace HMRequestFramework.xcworkspace -scheme HMRequestFramework -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty
- pod lib lint --quick

after_success: slather
